faq = {
    "Why is your product so cheap?": "There is a number of causes for that. We do not spend anything on marketing, there are no taxes to be paid as the product comes into the country unregistered, the company is located in an offshore zone and the production costs are way lower. No child labor is used.",
    "Do you sell branded medicines or generic pills?": "You may find both generic and branded products on our website. All generic items will be marked as 'generic' in your purchasing cart even if an original brand name is used.",
    "What pills do you sell?": "Please review the section entitled products in your browser, a full list of medications are available there, some medications are considered controlled substances, the law requires that before these medicines can be dispensed that you undergo a physical exam, this means we cannot sell them online. ",
    "What does Generic stand for?": "Generic means using another name for the same components. The contents of the pills are absolutely the same in our generic version and the branded analog.",
    "Why does the name printed on the pill differ from the branded one?": "The title you see printed on the pill in the active ingredient used here. The contents of the generic pills are completely the same as those of the branded versions. The difference is in the name only. The manufacturers of generic drugs cannot use the brand names on their pharmaceuticals as that would be the breach of copyright while using the familiar ingredients is thoroughly legal.",
    "Why does the shape of the pill differ from that of the branded one?": "The shapes differ for exactly the same reason as listed in the question above. The shape of the pill is the intellectual property of the manufacturer and reproducing it will qualify as the breach of copyright as well.",
    "What is the difference between Soft and Regular tabs?": "The difference lays in the rate of action (Soft tabs act faster than the Regular ones) and in the zone of absorption. Soft tabs dissolve under the tongue that allows you to take alcohol or eat fat meals prior to sexual intercourse, with regular tabs drinking is fully not recommended.",
    "What is the package like?": "The pills come in one or more blister packs containing 10 pills each. All orders under 60 pills are shipped in one package. Large orders can be split into 2 packs and come in 2 separate envelopes. The second part of a large order is dispatched in 3 days after the first one.",
    "Will you be offering other products in the future?": "If you need a product which is not mentioned at our site, you can let us know of the product you are interested in and we will try our best to add it to our list as soon as possible",
    "What happens when I submit my order?": "Your order is dispatched through our order system to a licensed physician who will review the data you have submitted and confirm or reject your request.",
    "What credit cards do you accept?": "We accept Visa, MasterCard, AmEx, Diners and JCB cards.",
    "When will my credit card be charged?": "Your credit card will be charged as soon as your order is processed and accepted by our billing section.",
    "What is your privacy policy?": "We are fully dedicated to your privacy and security. Please refer to the current privacy policy in the terms & conditions section of our order page.\n\nRest assured that our online order system makes use of the latest Security encryption technology to ensure that your credit card information is submitted safely and with the highest level of protection. All of our computer systems undergo regular security checks to ensure that our ordering system is properly protected.",
    "How can I apply the coupon?": "We have a coupon system which gives you an opportunity to have a discount for your purchase or receiving some extra products for free or free delivery option. If you receive on your mail a letter with coupon, simply apply it by pasting at checkout. Also, you are able to receive a coupon after your first purchase if it is equal or larger then 200 EUR. For further information, please contact us or ask your customer support manager when he/she will contact you after checkout.",
    "What is your cancellation policy?": "You may cancel your order before the order has shipped or been approved by the doctor. If the order has already been shipped or approved we cannot cancel your order. Please refer to the current cancellation policy in the terms & conditions section of our order page for more information.",
    "Do you have any age restriction?": "Unfortunately, we do not sell the goods to persons, who 18 years old and younger.",
    "How do you ship orders?": "We can offer 2 shipping methods at the moment:\n\nTrackable Courier Service: the packages sent by this postal service can be tracked by the tracking number supplied after the order is shipped. See Tracking Your Package for details. International Unregistered Airmail",
    "Do you ship Internationally?": "Yes, we ship Internationally at this time.",
    "What if my order is delayed at customs?": "In case your order is delayed at customs, they inform you of that. They ask the recipient to come and give them permission to open the parcel. At this point, it is examined and given to you. If you have any problems with getting your order, please let us know and we will try to resolve the problem.",
    "What am I to do if the package is damaged when I receive it or if it is missing?": "In this case, you are to contact our support team and notify of the problem. We will either resend the package or refund your payment. See our policies section."
}

shops = {'Europe Pharmacy': 'https://europe-pharmacy.com/',
         'Mypharmaworld': 'https://mypharmaworld.com',
         'Helpinghandpharmacy': 'https://helpinghandpharmacy.com/'
}
